### PR TITLE
Small UI fixes

### LINKED ISSUE #991: Small UI fixes
### Expected behaviour    
1. The media bar buttons should be in the navbar                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
![IMG_9485](https://user-images.githubusercontent.com/5843044/68747633-3b6ab300-05fb-11ea-9030-4ebc8da03b7c.PNG)
2. Capital letter should be only for the first word as seen in other file managers.
![IMG_9486](https://user-images.githubusercontent.com/5843044/68747831-a0bea400-05fb-11ea-877a-d7cc03140569.PNG)
3.  Folder selection isn't reflected in the tableview.
![IMG_9487](https://user-images.githubusercontent.com/5843044/68747892-be8c0900-05fb-11ea-838e-ed0ac22dff3e.PNG)

### Actual behaviour   
1. The media navbar is double the  normal size                     
2. Folder creation menu puts a capital letter at each word.
3. Folder selection isn't updated.                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
### Steps to reproduce                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
1. Go to media view.
2. Create a new folder.
3. Select a folder for auto upload. Check the folder name after selection (it doesn't change)
### iOS version
Tested on iOS 12 and iOS 13
### App version
Latest

### PR DESCRIPTION
**Pull request by immortal79**
Fixed #991
Removed double height navbar in mediaview + disabled autocapitalise each word + update path for auto upload folder selection

### CODE REVIEW

**Comment by immortal79** [comment]
Commit seems signed and I'm using XCode 10.3

**Comment by marinofaggiana** [comment]
@immortal79 please don't use the XCode for commit because do not signoff , use only the command line:  

git commit --signoff -m "description"

Cheers

**Comment by Joris73** [comment]
@marinofaggiana 
We don't use XCode for commit. We use Fork app.
But ok, in command line for the futur.

**Comment by marinofaggiana** [comment]
ok, please fix this PR.

**Pull request closed without merging**
