### PR TITLE
chore(zh-hans.lproj): fix a spelling error in localizable.strings of Simplified Chinese

### PR DESCRIPTION
**Pull request by beanpow**
fix "\_add_filenametype\_"

### CODE REVIEW

**Comment by marinofaggiana** [comment]
@rakekniven can you help @beanpow here ? thanks

**Comment by rakekniven** [comment]
Hello @beanpow ,

all translations for Nextcloud project are done at the Transifex platform.
Please join us there and make a suggestion for the string.
Link:
https://www.transifex.com/nextcloud/nextcloud/translate/#zh_HK/ios/155338342?q=key%3A_add_filenametype_

For better understanding please read https://help.nextcloud.com/t/translation-knowledge-valid-for-the-entire-nextcloud-project-wiki/51550/21 as well.

I sent a message to a chinese reviewer to have a look here as well.

**Comment by beanpow** [comment]
Ok, Fine. Thanks.

**Comment by rakekniven** [comment]
Answer from Transifex:

Hi hi,

Chinese, like other languages spoken in more than one country, has subdivisions depending on the country of use. Currently there are 3 defined in Transifex: zh_HK (for Hong Kong, traditional Chinese), zh_TW (for Taiwan, traditional Chinese) and zh_CN (for China, simplified Chinese).

The person requesting the change speaks simplified Chinese and should be directed to the Simplified Chinese resources at https://www.transifex.com/nextcloud/nextcloud/language/zh_CN/

Hope this helps.

Cheers

**Pull request closed without merging**
