### PR TITLE
Allows to build the custom brands

### PR DESCRIPTION
**Pull request by MorrisJobke**
With this custom builds are possible. Otherwise they fail with this:

```
...
In file included from /Users/morrisjobke/Projects/nextcloud/ios-test/iOSClient/UploadFromOtherUpp/CCUploadFromOtherUpp.m:26:
In file included from /Users/morrisjobke/Projects/nextcloud/ios-test/iOSClient/Brand/NCBridgeSwift.h:28:
/Users/morrisjobke/Projects/nextcloud/ios-test/iOSClient/Brand/CustomSwift.h:2:9: fatal error: 'Custom-Swift.h' file not found
#import "Custom-Swift.h"
        ^~~~~~~~~~~~~~~~
1 error generated.
```

Found together with @mario

### CODE REVIEW

**Comment by mario** [comment]
👍

**Comment by MorrisJobke** [comment]
cc @marinofaggiana

**Comment by marinofaggiana** [comment]
Oh Yes, true,  I have correct on "develop" and add note.

thx

**Comment by MorrisJobke** [comment]
For reference: 72eb9eeb26a701f95516a740d396cd72eea24aee

**Pull request closed without merging**
