### PR TITLE
Respect app locale in interface and when creating automatic subfolder / voice memos / scans if system locale not supported

### PR DESCRIPTION
**Pull request by fservida**
Related to #2302 
- Does fix the autoupload subfolders
- Does not fix the inconsistencies in the interface, not sure where to change...

Signed-off-by: Francesco Servida <git.fservida@gmail.com>

### CODE REVIEW

**Comment by fservida** [comment]
Included some more interface elements but more importantly filename generation for voice memos and document scans

**Comment by nanis94** [comment]
fservida:develop

**Review by nanis94 — COMMENTED** [review]
iOSClient/Utility/CCUtility.m master

**Comment by nanis94** [comment]
iOSClient/Utility/CCUtility.m

**Comment by nanis94** [comment]
iOSClient/Utility/CCUtility.m master

**Comment by mpivchev** [comment]
This seems like a non breaking change, although not sure how to test it. Should I approve it? @marinofaggiana @claucambra

**Comment by mpivchev** [comment]
No update here in a long time, closing for now.

**Pull request closed without merging**
