### PR TITLE
Make more file extensions editable

### LINKED ISSUE #471: New function: allow plain text editing for markdown (.md)
Hi.

I would like to suggest to extend the ability to edit plain text files to 
- Markdown files (ending .md, .markdown, ...)

It would enable the same functionality  to edit these files like the .txt files, so not much would have to be added. 

So I am not suggesting to add markdown functionality, just to treat text files with this ending (.md) like plain text files (.txt)

Related Issue: #162. #472

### LINKED ISSUE #472: New function: allow plain text editing for org-mode (.org)
Hi.

I would like to suggest to extend the ability to edit plain text files to

- Org Mode files (ending .org)

It would enable the same functionality to edit these files like the .txt files, so not much would have to be added.

So I am not suggesting to add org-mode functionality, just to treat text files with endings .org like plain text files (.txt)

Related Issue: #162. #471

### PR DESCRIPTION
**Pull request by ViViDboarder**
This is my first patch to Nextcloud iOS and I'm having difficulty testing (can't login with Simulator and can't compile for my device due to no developer account). Maybe someone else can verify this works or let me know how I can build and test.

Also happy to refactor a little bit. I'm not sure best practices here but tried to be DRY.

Fixes #471 and Fixes #472

### CODE REVIEW

**Comment by ViViDboarder** [comment]
Nevermind! Got the simulator to work with the old login method. Working as expected.

**Comment by MorrisJobke** [comment]
@marinofaggiana Please have a look at this.

**Comment by ViViDboarder** [comment]
Hey @marinofaggiana. Are there any edits you'd like me to make, or can this be merged? Thanks!

**Comment by marinofaggiana** [comment]
Hi @ViViDboarder  "MD",  "MARKDOWN" are not text file but required a particular editor.

**Comment by mario** [comment]
@marinofaggiana actually it's a text file written in a certain way.

I'm not so sure about how widespread this .org is though o.o

**Comment by marinofaggiana** [comment]
@mario a text editor for a markdown file is not a good job ... .org ? I don't know this extension

**Comment by mario** [comment]
@marinofaggiana I agree, but it's better to support it than not. Also, I doubt we'll ever have a real markdown editor inside the app :)

**Comment by ViViDboarder** [comment]
Markdown was created so that it could be written and read inside a plain text editor.

Also, it seems that the Nextcloud app thinks it's sufficient to view any kind of text file in a plain text viewer. As a user, I would expect to be able to edit them as well.

**Comment by mario** [comment]
That being said, please make sure a future PR uses mimetype so it can edit all known text files. :)

@marinofaggiana I vote for merging this at this moment 👍

**Comment by rakekniven** [comment]
@marinofaggiana I vote for merging this at this moment, too 👍

**Comment by ViViDboarder** [comment]
Any more thoughts on this?

**Comment by rakekniven** [comment]
Hello @ViViDboarder 
Currently there is a new version v2.21.0 in development, testing and should be out soon.

Next release will contain fixes and features like this.

**Comment by rakekniven** [comment]
@marinofaggiana Please include this in next release.

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/ios/issues/607#issuecomment-405489092

**Comment by rakekniven** [comment]
Works

**Pull request closed without merging**
