### PR TITLE
Landscape Share UI

### LINKED ISSUE #1770: Share screen not scrollable in landscape mode
Steps to Reproduce:
1. start the app
2. tap on any share icon next to a folder or file
3. rotate the device in landscape mode
4. try to scroll on the screen

Actual Results:
the page is not scrollable.

Expected Results:
the page is scrollable

### PR DESCRIPTION
**Pull request by thisIsTheFoxe**
Fix share UI so that when in landscape mode the shares can be scrolled.
- fixes #1770

### CODE REVIEW

**Comment by marinofaggiana** [comment]
This PR can take a very long time to complete, making the interface usable in landscape with iPhone is not easy and I don't even know how much it is worth ... is unusable 

Simulator Screen Shot - iPhone 13 - 2021-12-06 at 10 32 25
Simulator Screen Shot - iPhone 13 - 2021-12-06 at 10 31 09

**Review by marinofaggiana — CHANGES_REQUESTED** [review]
Do not works, job incomplete

**Comment by thisIsTheFoxe** [comment]
I am aware that it's not perfect. But I thought it might be a good start to at least have the table view displayed correctly for now as it was mentioned in the linked issue.


True, it would be nice to have the other share components work just as well in landscape but I think it might be easier to split that into multiple issue / PRs since otherwise, as you mentioned it would take forever..

Also, as you can see right now I'm trying to refactor the black MenuViews into NCMenus.. please let me know how think we should continue regarding this PR..

**Comment by marinofaggiana** [comment]
> @marinofaggiana I am aware that it's not perfect. But I thought it might be a good start to at least have the table view displayed correctly for now as it was mentioned in the linked issue.
> 
> True, it would be nice to have the other share components work just as well in landscape but I think it might be easier to split that into multiple issue / PRs since otherwise, as you mentioned it would take forever..
> 
> Also, as you can see right now I'm trying to refactor the black MenuViews into NCMenus.. please let me know how think we should continue regarding this PR..

We are the Nextcloud iOS team and we like to do things well, this PR is not priority but exactly its a good start, if you tried it and it has no problems i can approved it

**Comment by thisIsTheFoxe** [comment]
Closing this (at least for now) in favour of #1836

**Pull request closed without merging**
