### PR TITLE
Insert permission request for camera roll access in context

### PR DESCRIPTION
**Pull request by rygen**
A permission request for camera roll access is happening on app launch - together with notifications request - causing two alerts straight after each other, possibly leading to confusion. This commit removes it.
The permission is already being requested when access is really needed in CCMain.m (`PHPhotoLibrary requestAuthorization`), using the up-to-date iOS 8+ Photos framework, therefore making the call in AppDelegate.m unnecessary.

### CODE REVIEW

**Comment by marinofaggiana** [comment]
@rygen The request Authorization for camera roll it's necessary too for enable auto upload, please verify ... if i first do not openAssetsPickerController but  select Upload camera photos/videos ? 

thanks for verify

**Comment by rygen** [comment]
True, it was not allowing the camera upload to be activated without going to the system settings first. Thanks for the heads up! 
The last commit fixes it. I've inserted a second permission request in context, so that it is requested when the "Activate camera upload" button is tapped. This request is also using the latest API (iOS 8+).

**Comment by marinofaggiana** [comment]
mmm no, the permission must be check in Settings, view CCManageCameraUpload.m ;)

**Comment by rygen** [comment]
Ahh, sorry. Didn't see there was another entry point to the settings for automatic upload. Hopefully now it's being requested in the right place and providing the user a good context for such request :)

**Comment by marinofaggiana** [comment]
@rygen please wait, now i am worked for clear the code ;)

**Pull request closed without merging**
