### PR TITLE
Fixed layout bugs and enabled split screen on iPad

### PR DESCRIPTION
**Pull request by clemens-schulz**

### CODE REVIEW

**Comment by jancborchardt** [comment]
@clemens-schulz nice, welcome to Nextcloud! :)

@marinofaggiana please review ;)

**Comment by jancborchardt** [comment]
Also cc the whole @nextcloud/ios team for review

**Comment by marinofaggiana** [comment]
@clemens-schulz welcome, review soon !

**Comment by marinofaggiana** [comment]
@clemens-schulz the modify on EAIntroView it's for version to 2.10 ?

**Comment by clemens-schulz** [comment]
@marinofaggiana It's not 2.10, but the fix is identical to 2.10 minus a few other minor changes. I just didn't check for a newer version before fixing it.
I'm not sure how you keep track of dependencies, but there should be no problem just replacing it with 2.10.

**Comment by marinofaggiana** [comment]
@clemens-schulz i think which is better wich we using the last EAIntroView 2.10 (22 days ago), what do you think? 

note : this version it's virtually closed, have you found problems ?

**Comment by clemens-schulz** [comment]
@marinofaggiana I agree that using EAIntroView 2.10 is better.
Which version are you referring to?

**Comment by marinofaggiana** [comment]
@clemens-schulz  this 2.15 it's in test from .... 10 day

**Comment by clemens-schulz** [comment]
@marinofaggiana Found only the two I fixed.

**Comment by marinofaggiana** [comment]
👍 @clemens-schulz  please new PR without Libraries external/EAIntroView/EAIntroView.m

**Comment by clemens-schulz** [comment]
@marinofaggiana Ok, see #5

**Pull request closed without merging**
