### PR TITLE
i18n: Change to capital letter

### PR DESCRIPTION
**Pull request by Valdnet**
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Review by rakekniven — COMMENTED** [review]
WiFi or Wi-Fi ?

**Comment by marinofaggiana** [comment]
Hi, @Valdnet thanks but this is intentional.

**Comment by marinofaggiana** [comment]
> WiFi or Wi-Fi ?

mmm better Wi-Fi ... maybe ...

**Comment by rakekniven** [comment]
> > WiFi or Wi-Fi ?
> 
> mmm better Wi-Fi ... maybe ...

Will you change this?
Or should I provide an PR?

**Comment by Valdnet** [comment]
> WiFi or Wi-Fi ?

@rakekniven Well caught error 👍.

> but this is intentional.

@marinofaggiana OK. After checking the code, it seemed to be capitalized. Restored again.

**Comment by marinofaggiana** [comment]
> > > WiFi or Wi-Fi ?
> > 
> > 
> > mmm better Wi-Fi ... maybe ...
> 
> Will you change this? Or should I provide an PR?

make I thanks

**Comment by Valdnet** [comment]
@marinofaggiana Do I think well in the post above?

**Comment by marinofaggiana** [comment]
@Valdnet fixed. thanks

**Comment by Valdnet** [comment]
@marinofaggiana See also that the text string should also begin with a capital letter: `network reachable via Wi-Fi or cable`
Waiting for: **N**etwork reachable via Wi-Fi or cable

To be consistent with a text string:
`Waiting for: User: user_name in url_address`

**Comment by Valdnet** [comment]
@marinofaggiana Ah. Okay 😉. Generally, the colon next to the user is unnecessary when it comes with the text string `Waiting for:`.

In my opinion it should be: `Waiting for: user user_name in url_address`.

Sorry to be grumbling, but I would like to normalize them 😉.

**Comment by marinofaggiana** [comment]
Fixed, thankss

**Pull request closed without merging**
