### PR TITLE
Changed zoom button behaviour

### PR DESCRIPTION
**Pull request by immortal79**
The old zoom button in the media view had a bad UX behaviour. This is an attempt to mitigate the issue (for the moment + and - are used as button title but it would maybe need new icons).

New UI:
Jun-09-2020 11-09-14

Signed-off-by: Philippe Weidmann <philippe.weidmann@infomaniak.com>

### CODE REVIEW

**Comment by marinofaggiana** [comment]
I think that for the future the simple Apple logic is the best :

**Comment by immortal79** [comment]
I also agree

**Comment by marinofaggiana** [comment]
Note: @immortal79 the behavior of + and - is inverted ...

**Comment by immortal79** [comment]
Ooops fixing asap

**Comment by marinofaggiana** [comment]
@now don't works  .. bad :-)

**Comment by immortal79** [comment]
Ooops #2 I forgot to invert some logic...

**Comment by immortal79** [comment]
Should be good now

**Pull request merged**
