### PR TITLE
Fix black text on dark background in account switcher

### LINKED ISSUE #1197: Black text on black background in account switcher
### Expected behaviour
White text on dark background  in the account switcher/ wheel if dark mode is enabled.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

### Actual behaviour
When using the dark mode on my iPad the account switcher is always black text on dark 
background. It is nearly unreadable. 
This behavior also exists, if the detection of iOS dark mode is disabled. The account switcher 
gets dark even the rest of the app is in light mode.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              


### Steps to reproduce 
setup two account in the nextcloud iOS app and try to switch accounts    

### iOS version
iPadOS 13.4

### App version
2.25.9.2

**Nextcloud version:** (see Nextcloud admin page)
18.0.3, 18.0.1.3

### PR DESCRIPTION
**Pull request by onehappycat**
Fix #1197.

Signed-off-by: onehappycat <one.happy.cat@gmx.com>

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@marinofaggiana mind to check out this contribution?

**Comment by onehappycat** [comment]
Changed to use NCBrandColor.sharedInstance's setting instead of UIColor's labelColor. I assume this is preferable, @marinofaggiana?

**Comment by marinofaggiana** [comment]
Hi @onehappycat sorry for delay, I was busy, today I check :-)

**Comment by marinofaggiana** [comment]
Thanks @onehappycat good works!! thanks a lot for your help

**Pull request merged**
