### PR TITLE
Revert "Talk notification"

### PR DESCRIPTION
**Pull request by thisIsTheFoxe**
Reverts nextcloud/iOS#1768
Due to unpublished AppSotre version..? @marinofaggiana 

TODO:
- [x] DCO

### CODE REVIEW

**Comment by marinofaggiana** [comment]
When approved I can merge the develop -> Master :-) so the develop is ready for a new version

**Comment by thisIsTheFoxe** [comment]
@marinofaggiana Ok, but for the future, please let me know ahead of time..

Also, since this is an open source project and to help improve communication, I suggest we open a *develop > master* PR as soon as possible, whenever we plan to release a new version. That will make it easier to get feedback and make it clearer that we may put a hold on some issues / PRs until the new version is fully published. Wdyt?

**Comment by marinofaggiana** [comment]
| develop > master PR as soon as possible

What's do you mean ?

**Review by marinofaggiana — APPROVED** [review]

**Comment by marinofaggiana** [comment]
Tested by @Ivansss

**Pull request merged**
