### PR TITLE
Fix for navbar behavior

### PR DESCRIPTION
**Pull request by immortal79**
It's a lot like the previous commit which was reverted but I added some fixes which should prevent the behaviours with the overlapping tableview/header you described.

If you find some cases where the sort header is not correct tell me how to reproduce the bug so that I can fix it.

Signed-off-by: Philippe Weidmann <philippe.weidmann@infomaniak.com>

### CODE REVIEW

**Comment by marinofaggiana** [comment]
@immortal79 change the object from UIViewController to UITableViewController is so important for ?

**Comment by immortal79** [comment]
As it's the way Apple "intended" it, it resolves a lot of bugs and layout issues with large titles / table header and search controller.

**Comment by immortal79** [comment]
Also fixes #1307 ^^

**Comment by marinofaggiana** [comment]
ahha

**Pull request merged**
