### PR TITLE
Feature: Go to a page within PDF.

### PR DESCRIPTION
**Pull request by itsaboutcode**
I have implemented this feature for PDF files where I would like to go to any page in the PDF. 

@marinofaggiana - To qualify it for master, we will need an image for the actionsheet and localization for all the supported languages.

### CODE REVIEW

**Comment by eibex** [comment]
I do not know Object-C, but wouldn't it be cleaner for a page selector to appear instead? (e.g. picture)
This would also remove the possibility of entering an invalid page.
image

**Comment by marinofaggiana** [comment]
@itsaboutcode ohhh thanks for your tribute, very appreciated !! 
@eibex yes true but the select number would require more job ... @itsaboutcode what do you think ?

Note: @itsaboutcode it would be better to use the develop branch

**Comment by itsaboutcode** [comment]
@marinofaggiana - I think spinner will require more effort on user part.

I did not knew branch should be taken from develop branch. I will take care of it in my next contribution.

**Comment by marinofaggiana** [comment]
Thanks !!

**Comment by marinofaggiana** [comment]
merged in develop, thanks

**Comment by itsaboutcode** [comment]
@marinofaggiana - Thanks for merging. But it's not complete yet. Icon and localization would be required.

**Comment by marinofaggiana** [comment]
@itsaboutcode done. look the code in develop branch ;-)

**Pull request closed without merging**
