### PR TITLE
Fix for #1102

### PR DESCRIPTION
**Pull request by immortal79**
This PR should fix regression as discussed in #1102

@marinofaggiana Can you test that it's working ? I cannot test as I don't have a server on NextCloud 18.
The 'Add folder info' button appears in the create menu (+)

### CODE REVIEW

**Comment by immortal79** [comment]
Please review 2834d46 and 733ae33
6dbe41e only changes indentation

**Comment by marinofaggiana** [comment]
Good works.

**Comment by marinofaggiana** [comment]
@immortal79 when do you have time remain the replace for offline menu and delete menu and the remove of old code/library (library/remenu, framework: danielsaidi/Sheeeeeeeeet).

Another small thing : can you create all class with the NC suffix, for example MainMenuTableViewController should be NCMainMenuTableViewController (.swift)

thanks

**Comment by immortal79** [comment]
Ok, gonna do that Monday :)

**Comment by marinofaggiana** [comment]
@immortal79  look:

https://github.com/nextcloud/ios/commit/748248fc974424d09cdd03d462616a55f629530d
https://github.com/nextcloud/ios/commit/669d683927003e363bb5deb2ea1ff1eee516127d
https://github.com/nextcloud/ios/commit/d58470d85ff000859954e3cfe8c087f30337dea8

**Pull request merged**
