### PR TITLE
Fix intro for #1065

### PR DESCRIPTION
**Pull request by immortal79**
As mentioned in #1065, this PR fixes several problems with the actual intro.

Signed-off-by: Philippe Weidmann philippe.weidmann@infomaniak.com

### CODE REVIEW

**Comment by marinofaggiana** [comment]
Its complex, I prefer merge it into newintro for test :-) thanks

**Comment by immortal79** [comment]
Yes I also think it's better  😊. I might have forgot some things as the intro is called from a lot of places in a lot of different states.

**Comment by marinofaggiana** [comment]
Yes, because exists version (brand) without Intro or with Intro modified, but it is appropriate to review the code to streamline it

**Comment by marinofaggiana** [comment]
@immortal79 good job! great ! Insert in develop, only some formal change. 

P.S. next week we are in Berlin for a hack week, are you available for a meeting ?

**Pull request merged**
