### PR TITLE
Menu displayed as drawer

### PR DESCRIPTION
**Pull request by immortal79**
I replaced the actual menu everywhere with a more intuitive, accessible and modern bottom drawer.
New icons were added to better represent possible actions.

When creating a new document :
Simulator Screen Shot - iPhone 11 - 2020-01-24 at 14 46 42

When clicking (...) for a document :
Simulator Screen Shot - iPhone 11 - 2020-01-24 at 14 46 37

Select menu :
Simulator Screen Shot - iPhone 11 - 2020-01-24 at 14 46 48

### CODE REVIEW

**Comment by marinofaggiana** [comment]
Very good ! do you have removed the ReMenu dependence?

**Comment by immortal79** [comment]
No, I wanted to get your approval first :)

**Comment by marinofaggiana** [comment]
No we can remove it after, do you have test it with iPad ?

**Comment by immortal79** [comment]
Yes I made it look like this:
Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2020-01-24 at 15 21 47
Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2020-01-24 at 15 21 52

**Comment by marinofaggiana** [comment]
Great !

**Comment by marinofaggiana** [comment]
@immortal79 Next week I start with iPad single & standard bar button (as spoken)

**Comment by marinofaggiana** [comment]
now you can remove the old ReMenu

**Pull request merged**
