### PR TITLE
New Share UI

### LINKED ISSUE #1770: Share screen not scrollable in landscape mode
Steps to Reproduce:
1. start the app
2. tap on any share icon next to a folder or file
3. rotate the device in landscape mode
4. try to scroll on the screen

Actual Results:
the page is not scrollable.

Expected Results:
the page is scrollable

### PR DESCRIPTION
**Pull request by thisIsTheFoxe**
This PR uses #1846 (which again is based off of #1799) and also adopts the features and ideas of #1836

Fix #1770

Furthermore this PR allows users to set the permissions **before** creating a share (but not with increase permissions). Which seems to be the cause of #1228 and #255.

### CODE REVIEW

**Comment by marinofaggiana** [comment]
Simulator Screen Shot - iPhone 13 - 2022-04-12 at 14 39 01

The favorite icon (button) do not works

**Comment by marinofaggiana** [comment]
Simulator Screen Shot - iPhone 13 - 2022-04-12 at 14 41 25

I would remove the wording Sharing (duplicate) in its place I would put the Notes to recipient with the textfield more attached to the Note to re...

**Comment by marinofaggiana** [comment]
Simulator Screen Shot - iPhone 13 - 2022-04-12 at 15 19 59

- Note: translate error, is better more line and ... why I can't allow resharing and editing  ?

**Comment by marinofaggiana** [comment]
UI-X
- favorite button: or remove it or (for coherence) must be an button (favorite yes / no)  
- Font options: can you try with some point in less 
- Cancel line: can you try with size 1 
 
Simulator Screen Shot - iPhone 13 - 2022-04-21 at 10 08 21

**Comment by thisIsTheFoxe** [comment]
> Font options: can you try with some point in less

It uses the default system font (which by default is 16pt) which is the same as NCMenu and NCMore. But most importantly is reacts to Dynamic Type. So you can set the size yourself in the settings. I think that's a good point to start (also considering  #621).

> Cancel line: can you try with size 1

I did. it's less prominent and has not enough contrast. Imo 2pt is clearer.

@marinofaggiana If everything works please approve this PR.

**Comment by marinofaggiana** [comment]
> > Font options: can you try with some point in less
> 
> It uses the default system font (which by default is 16pt) which is the same as NCMenu and NCMore. But most importantly is reacts to Dynamic Type. So you can set the size yourself in the settings. I think that's a good point to start (also considering #621).
> 
> > Cancel line: can you try with size 1
> 
> I did. it's less prominent and has not enough contrast. Imo 2pt is clearer.
> 
> @marinofaggiana If everything works please approve this PR.

Good, I do some share testing

**Comment by marinofaggiana** [comment]
- Good!, but for Apple (And Nextcloud) users Cancel is on the left of Action-OK-Save-Share-blabla button.

Simulator Screen Shot - iPhone 13 - 2022-04-22 at 09 58 40

- The Cancel message appears even though I haven't changed anything

Schermata 2022-04-22 alle 10 05 38

- Can you up the bar (safeArea) and Done -> Right, Clear <- Left :-)

Schermata 2022-04-22 alle 10 08 21

**Comment by jancborchardt** [comment]
Some points:
- The permissions on top are not "Advanced", they are " Permissions"
- "Miscellaneous" is the actual "Advanced" section, and can be put in a subsection that needs to be navigated to. Otherwise everything looks important
- The share button does not look like it has the same color as the folder icon – aren't both themed?
- The buttons don't look iOS style, but I might be wrong

@Ivansss can you check this too for iOS design? And @thisIsTheFoxe before/after screenshots help for easier design review :)

**Comment by thisIsTheFoxe** [comment]
@jancborchardt thanks. And [here's](https://user-images.githubusercontent.com/18512366/165687325-24d7fca9-4c38-4b17-ac96-a1cd3cc3f2eb.jpeg) how the permissions looked before, or how they look currently.

> - The buttons don't look iOS style, but I might be wrong

For larger buttons like that Apple seems to prefers rounded corner style buttons (e.g. Maps direction & end route button). The fully rounded buttons fit with the Nextcloud (web) design.

**Comment by marinofaggiana** [comment]
> @jancborchardt thanks. And [here's](https://user-images.githubusercontent.com/18512366/165687325-24d7fca9-4c38-4b17-ac96-a1cd3cc3f2eb.jpeg) how the permissions looked before, or how they look currently.
> 
> > * The buttons don't look iOS style, but I might be wrong
> 
> For larger buttons like that Apple seems to prefers rounded corner style buttons (e.g. Maps direction & end route button). The fully rounded buttons fit with the Nextcloud (web) design.

The buttons are correctly.
@thisIsTheFoxe about @thisIsTheFoxe [Implement share permission discard changes only when changed] I have still issue (shared link)

**Comment by marinofaggiana** [comment]
**Via web**

Schermata 2022-04-29 alle 14 26 55

**Via iOS**

Simulator Screen Shot - iPhone 13 - 2022-04-29 at 14 26 40

@thisIsTheFoxe where is the "Share link" ?

**Review by marinofaggiana — CHANGES_REQUESTED** [review]
BUG: Please correct and test it.

**Comment by thisIsTheFoxe** [comment]
@marinofaggiana I'm sorry I wan't able to reproduce this. The add button is always there unless you don't have re-share permission, which will show a different message in the search bar. Please check again and provide further details if possible

**Comment by marinofaggiana** [comment]
> @marinofaggiana I'm sorry I wan't able to reproduce this. The add button is always there unless you don't have re-share permission, which will show a different message in the search bar (same as web). Please check again and provide further details if possible

ok! I debug.

**Comment by marinofaggiana** [comment]
| ok! I debug.

ops. I can't reproduce ... Probably my DB dirty :(
But I have found this:

https://user-images.githubusercontent.com/8616947/166263666-38efdc07-37e2-4b11-aaf4-b9718afe8397.mov

Note UI: when I touch Done in "Note to recipient" why don't it goback ?

**Review by marinofaggiana — CHANGES_REQUESTED** [review]
Please look the video

**Comment by thisIsTheFoxe** [comment]
> Please look the video

again, not able to reproduce this. Is this related to adding the note? Is the note added? Please check again and provide the server response if possible. Also, note that some errors (e.g. bad password) are provided from the server and will be fixed eventually in #1909.

> Note UI: when I touch Done in "Note to recipient" why don't it goback ?

see https://github.com/nextcloud/ios/pull/1931#issuecomment-1096860517

**Comment by marinofaggiana** [comment]
> > Please look the video
> 
> again, not able to reproduce this. Is this related to adding the note? Is the note added? Please check again and provide the server response if possible. Also, note that some errors (e.g. bad password) are provided from the server and will be fixed eventually in #1909.
> 

UUU sorry for noise I have change server ... now works. Sorry

> > Note UI: when I touch Done in "Note to recipient" why don't it goback ?
> 
> see [#1931 (comment)](https://github.com/nextcloud/ios/pull/1931#issuecomment-1096860517)

Note. @thisIsTheFoxe can you add the icon here:

Schermata 2022-05-04 alle 10 37 08

**Comment by thisIsTheFoxe** [comment]
@marinofaggiana no problem.

> Note. [...] can you add the icon here:

You mean the pencil for editing? Good idea, but I'd do that together with adding a new icon for "View only" (e.g. the SFSymbol: *eye*). And I think that's a good point to come back to later. This PR is mainly about the new share / edit share view.

**Comment by marinofaggiana** [comment]
Ok, we can add this in develop for more testing in TestFlight! Thanks a lot

**Review by marinofaggiana — APPROVED** [review]

**Pull request merged**
