### PR TITLE
Fixed UI bug and enabled split screen on iPad

### PR DESCRIPTION
**Pull request by clemens-schulz**
See PR #2 for details

### CODE REVIEW

**Comment by marinofaggiana** [comment]
Thanks @clemens-schulz (b4a7b8f) thanks add, but the "Enabled support for split screen on iPad" has a problem with name, do not change Name file : LaunchScreenNextcloud.xib, please align version.

**Comment by jancborchardt** [comment]
Btw @clemens-schulz I added you to the https://github.com/nextcloud organization so you should be able to also create branches in this repository directly for easier collaboration. :)

**Comment by jancborchardt** [comment]
@clemens-schulz any update here? :)

**Comment by marinofaggiana** [comment]
@clemens-schulz please review : 

https://github.com/nextcloud/ios/pull/5/commits/ba1534d2d57ad35792cbbfbd784afe489b189e97

too many changes from this version .. sorry.

**Pull request closed without merging**
