### PR TITLE
Show modification date for files older than 30 days

### PR DESCRIPTION
**Pull request by wolframroesler**
As mentioned in #636, for files older than 30 days the iOS client now displays the file modification date rather than the "over 30 days" message (in human-readable, locale-specific format).

bildschirmfoto 2018-12-21 um 10 14 24

### CODE REVIEW

**Comment by jancborchardt** [comment]
@wolframroesler very nice, thanks for the initiative of directly submitting a pull request! Welcome to Nextcloud! :tada: 

Only one tiny piece of feedback: Currently the comma placement is a bit off

> Aug 3, 2016 165 bytes

mixes the year and the file size. Instead it could be:

> Aug 3 2016, 165 bytes



Also @nextcloud/android what do you think about this? We should do the same across our mobile apps.

**Comment by jancborchardt** [comment]
Also @TecJon @rakekniven please review as this fixes the issue https://github.com/nextcloud/ios/issues/636 you were involved in too. :) And cc @nextcloud/ios for review.

**Comment by tobiasKaminsky** [comment]
On Android we rely on android's built in relative timestamp:
- show x days ago (until 7 days)
- within the same year, show only "03. March"
- otherwise show complete date, e.g. 20.12.2013

**Comment by wolframroesler** [comment]
@jancborchardt thanks for your reply.

> Only one tiny piece of feedback: Currently the comma placement is a bit off

You're right, there should be a comma between the date and the size, but then there should also be a comma between the age and the size (for files younger than a month) to make it consistent. Will look into it.

As for the comma between date and year, that one comes from the locale-specific date formatting function (`setDateStyle:NSDateFormatterMediumStyle`) so we've got little control over that, and little chance to get rid of it (unless we do some ugly string manipulation stuff which may or may not work in other locales). Here's how it looks like when the phone is switched to German:

bildschirmfoto 2018-12-21 um 16 35 45

**Comment by wolframroesler** [comment]
@tobiasKaminsky 

> * show x days ago (until 7 days)
> * within the same year, show only "03. March"
> * otherwise show complete date, e.g. 20.12.2013

Does anyone know if iOS has a similar functionality? It would be nice if it were consistent with the Android version, however we need to use some operating system functionality in order to get locale-specific formatting right.

**Comment by wolframroesler** [comment]
@jancborchardt by the way, thanks for the welcome, allow me to introduce myself. I'm a veteran software developer, located in Germany, doing C++ on Linux for a living, self-hosted Nextcloud in my bedroom, and the "over 30 days" thing has been bugging me for a long time. Decided to fix it in my winter vacation, was happy to find that someone else had already filed an issue for it. Nextcloud is a central part of my private IT infrastructure, I'm glad to contribute and thus return a bit to the community.

**Comment by TecJon** [comment]
The screenshot with the comma looks good to me.

**Comment by jancborchardt** [comment]
Nice @wolframroesler! @marinofaggiana is the @nextcloud/ios lead and we could really use more community contributors on the iOS app, so any contribution is very very welcome! :)

Also cc @Ivansss @nextcloud/ios for review

**Comment by marinofaggiana** [comment]
@wolframroesler 👏 good job ! You are welcome and your help is much appreciated !

**Comment by wolframroesler** [comment]
@marinofaggiana Thanks! My resources are limited by I'm glad to be of service.

Are there already plans for when the next version of the iOS app will be released?

**Comment by marinofaggiana** [comment]
@wolframroesler January 2019 in TestFlight

**Pull request merged**
