### PR TITLE
Improve auto upload file mask

### PR DESCRIPTION
**Pull request by c4539**
This change makes the separator before and after the time string configurable.

### CODE REVIEW

**Comment by c4539** [comment]
This should close #359

**Comment by c4539** [comment]
@marinofaggiana Do you think this can be included at some point? With one of the last updates, the nomenclature of the Auto-Upload files has been changed and since then, it's no longer possible to have a space after the timestring (which used to be the default). Thanks.

**Comment by marinofaggiana** [comment]
@c4539 Simon change te code only for improvement but not for modify the actual "default" filename ... the users do not want changes

**Comment by c4539** [comment]
@marinofaggiana how about changing the trim only? Shouldn’t change anything to the default configuration but enables users to use a white space as the separate between the timestring and the file number.

**Comment by marinofaggiana** [comment]
@c4539 try ;)

**Comment by c4539** [comment]
@marinofaggiana Thanks a lot, works like a charm ;-)

**Pull request closed without merging**
