### PR TITLE
Update NCLoginWeb.swift

### LINKED ISSUE #1791: Nextcloud 4.1.0 IpadOS issue with all servers
### Steps to reproduce

1. Installation Nextcloud iPadOS 4.1.0 on iPad Pro M1
2. logging to my private Nextcloud server installed on RaspberryPi --> host "https://dwpcloud.xxx.xxx" and access button is displayed
3. After button clicked: welcome page works with user/password invitation for logging

### Expected behaviour
 
After user/password validation in Nextcloud iPadOS app: a dashboard is displayed correctly

### Actual behaviour

After user/password validation in Nextcloud iPadOS app message display as below:
"**Internal Server Error**
_This server was unable to complete your request.
If this happens again, please send the technical details below to the server administrator.
More details can be found in the server log._"

### Remarks

I've installed **Nextcloud iOS 4.1.0 in iphone12pro** (iOS15.1.1) : everything works fine with NextcloudPi/RaspberryPi !
I've tried to connect to Nextcloud server with **Safari installed in iPadPro M1** (same tablet used for Nextcloud iPadOS 4.1.0) :  everything works fine with NextcloudPi/RaspberryPi !

I've tested with other Nextcloud server (Server company name "cloud.esrf.fr") : I have same "Internal Server Error" issue after user/password logging with Nextcloud iPadOS app but works fine with **Safari/iPad Pro M1 and Nextcloud iOS app/iPhone12pro** !

Uninstall of Nextcloud iPadOS app, clean restart iPadPro and download/install Nextcloud iPadOS app : same behaviour described above nothing changed with both servers.

### Reasoning or why should it be changed/implemented?

How explain on same  iPadPro M1 tablet that Nextcloud running on **Safari** works fine but not with **Nextcloud iPadOS** app on different Nextcloud servers (private and professional) ? This issue didn't exist with previous Nextcloud iPadOS version 4.0.6 ...

### Environment data

**iOS version:**  iOS 15.1

**Nextcloud app:**  iPadOS 4.1.0

**Server operating system:** linux 5.10.63-v8 aarch64 (raspberry)

**Web server:** Apache

**PHP version:** 7.3.31

**Database:**  MariaDB

**Nextcloud version:** 22.2.2

### LINKED ISSUE #1800: Can‘t log in if device name includes Umlaut
### Steps to reproduce

1. Have Umlaut such as é in device name
2. Try to login
3. ??

### Expected behaviour

Log in successfully

### Actual behaviour

I get the following error: An exception occurred while executing a query: SQLSTATE[22021]: Character not in repertoire: 7 ERROR: invalid byte sequence for encoding "UTF8": 0xe9 0x64 0x72

### Screenshots

F705DE8A-0861-44D8-A8FB-8FC64DC9C377
A6284F1D-0D26-4CC4-98C5-76577F987AE0

### Logs

I can‘t get logs right now as I‘m not home.
 But it seems related to the following issue: https://github.com/nextcloud/server/issues/11177

### Reasoning or why should it be changed/implemented?
I want to keep my device name.

### Environment data

**iOS version:** 15.1

**Nextcloud iOS app version:** 4.1.0

**Server operating system:** Docker

**Web server:** nginx

**Database:** Postgresql 13.5

**PHP version:** 8.0

**Nextcloud version:** 23.0

### LINKED ISSUE #1803: login error bei Umlaut and iOS App
### Steps to reproduce

1. iOS-APP with umlaut in device i.e. ö, database postgreSQL
2. Try to login
3. error in syslog

### Expected behaviour

Login should be possible.

### Actual behaviour

Tell was what instead happens.

### Screenshots

If applicable, add a screenshot showing the issue.

### Logs

``` syslog
Dec  5 16:31:42 syncloud snapd[362]: 2021/12/05 16:31:42.134555 store.go:749: search query:
Dec  5 16:31:42 syncloud nextcloud.postgres[27444]: [4-1] 2021-12-05 16:31:42.709 GMT [27444] ERROR:  invalid byte sequence for encoding "UTF8": 0xf6 0x72 0x67 0x20
Dec  5 16:31:42 syncloud nextcloud.postgres[27444]: [4-2] 2021-12-05 16:31:42.709 GMT [27444] STATEMENT:  INSERT INTO "oc_authtoken" ("uid", "login_name", "public_key", "private_key", "password", "name", "token", "type", "remember", "last_activity", "last_check", "version") VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
Dec  5 16:31:42 syncloud Nextcloud[26304]: {"reqId":"IjbaYIcpGZ6eMNTFmk5a","level":3,"time":"2021-12-05T16:31:42+00:00","remoteAddr":"192.168.XXX.XXX","user":"joerg.XXXX","app":"index","method":"POST","url":"/login","message":"{\"Exception\":\"OC\\\\DB\\\\Exceptions\\\\DbalException\",\"Message\":\"An exception occurred while executing a query: SQLSTATE[22021]: Character not in repertoire: 7 ERROR:  invalid byte sequence for encoding \\\"UTF8\\\": 0xf6 0x72 0x67 0x20\",\"Code\":7,\"Trace\":[{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php\",\"line\":335,\"function\":\"wrap\",\"class\":\"OC\\\\DB\\\\Exceptions\\\\DbalException\",\"type\":\"::\",\"args\":[{\"__class__\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\"}]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/public/AppFramework/Db/QBMapper.php\",\"line\":139,\"function\":\"executeStatement\",\"class\":\"OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder\",\"type\":\"->\",\"args\":[]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/private/Authentication/Token/PublicKeyTokenProvider.php\",\"line\":88,\"function\":\"insert\",\"class\":\"OCP\\\\AppFramework\\\\Db\\\\QBMapper\",\"type\":\"->\",\"args\":[{\"id\":null,\"__class__\":\"OC\\\\Authentication\\\\Token\\\\PublicKeyToken\"}]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/private/Authentication/Token/Manager.php\",\"line\":70,\"function\":\"generateToken\",\"class\":\"OC\\\\Authentication\\\\Token\\\\PublicKeyTokenProvider\",\"type\":\"->\",\"args\":[\"*** sensitive parameters replaced ***\"]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/private/User/Session.php\",\"line\":690,\"function\":\"generateToken\",\"class\":\"OC\\\\Authentication\\\\Token\\\\Manager\",\"type\":\"->\",\"args\":[\"*** sensitive parameters replaced ***\"]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/private/Authentication/Login/CreateSessionTokenCommand.php\",\"line\":69,\"function\":\"createSessionToken\",\"class\":\"OC\\\\User\\\\Session\",\"type\":\"->\",\"args\":[\"*** sensitive parameters replaced ***\"]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/private/Authentication/Login/ALoginCommand.php\",\"line\":40,\"function\":\"process\",\"class\":\"OC\\\\Authentication\\\\Login\\\\CreateSessionTokenCommand\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\Authentication\\\\Login\\\\LoginData\"}]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/private/Authentication/Login/CompleteLoginCommand.php\",\"line\":48,\"function\":\"processNextOrFinishSuccessfully\",\"class\":\"OC\\\\Authentication\\\\Login\\\\ALoginCommand\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\Authentication\\\\Login\\\\LoginData\"}]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/private/Authentication/Login/ALoginCommand.php\",\"line\":40,\"function\":\"process\",\"class\":\"OC\\\\Authentication\\\\Login\\\\CompleteLoginCommand\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\Authentication\\\\Login\\\\LoginData\"}]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/private/Authentication/Login/LoggedInCheckCommand.php\",\"line\":60,\"function\":\"processNextOrFinishSuccessfully\",\"class\":\"OC\\\\Authentication\\\\Login\\\\ALoginCommand\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\Authentication\\\\Login\\\\LoginData\"}]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/private/Authentication/Login/ALoginCommand.php\",\"line\":40,\"function\":\"process\",\"class\":\"OC\\\\Authentication\\\\Login\\\\LoggedInCheckCommand\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\Authentication\\\\Login\\\\LoginData\"}]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/private/Authentication/Login/EmailLoginCommand.php\",\"line\":58,\"function\":\"processNextOrFinishSuccessfully\",\"class\":\"OC\\\\Authentication\\\\Login\\\\ALoginCommand\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\Authentication\\\\Login\\\\LoginData\"}]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/private/Authentication/Login/ALoginCommand.php\",\"line\":40,\"function\":\"process\",\"class\":\"OC\\\\Authentication\\\\Login\\\\EmailLoginCommand\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\Authentication\\\\Login\\\\LoginData\"}]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/private/Authentication/Login/UidLoginCommand.php\",\"line\":54,\"function\":\"processNextOrFinishSuccessfully\",\"class\":\"OC\\\\Authentication\\\\Login\\\\ALoginCommand\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\Authentication\\\\Login\\\\LoginData\"}]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/private/Authentication/Login/ALoginCommand.php\",\"line\":40,\"function\":\"process\",\"class\":\"OC\\\\Authentication\\\\Login\\\\UidLoginCommand\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\Authentication\\\\Login\\\\LoginData\"}]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/private/Authentication/Login/UserDisabledCheckCommand.php\",\"line\":58,\"function\":\"processNextOrFinishSuccessfully\",\"class\":\"OC\\\\Authentication\\\\Login\\\\ALoginCommand\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\Authentication\\\\Login\\\\LoginData\"}]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/private/Authentication/Login/ALoginCommand.php\",\"line\":40,\"function\":\"process\",\"class\":\"OC\\\\Authentication\\\\Login\\\\UserDisabledCheckCommand\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\Authentication\\\\Login\\\\LoginData\"}]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/private/Authentication/Login/PreLoginHookCommand.php\",\"line\":53,\"function\":\"processNextOrFinishSuccessfully\",\"class\":\"OC\\\\Authentication\\\\Login\\\\ALoginCommand\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\Authentication\\\\Login\\\\LoginData\"}]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/private/Authentication/Login/Chain.php\",\"line\":108,\"function\":\"process\",\"class\":\"OC\\\\Authentication\\\\Login\\\\PreLoginHookCommand\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\Authentication\\\\Login\\\\LoginData\"}]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/core/Controller/LoginController.php\",\"line\":314,\"function\":\"process\",\"class\":\"OC\\\\Authentication\\\\Login\\\\Chain\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\Authentication\\\\Login\\\\LoginData\"}]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/private/AppFramework/Http/Dispatcher.php\",\"line\":217,\"function\":\"tryLogin\",\"class\":\"OC\\\\Core\\\\Controller\\\\LoginController\",\"type\":\"->\",\"args\":[\"*** sensitive parameters replaced ***\"]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/private/AppFramework/Http/Dispatcher.php\",\"line\":126,\"function\":\"executeController\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\Core\\\\Controller\\\\LoginController\"},\"tryLogin\"]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/private/AppFramework/App.php\",\"line\":156,\"function\":\"dispatch\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\Core\\\\Controller\\\\LoginController\"},\"tryLogin\"]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/private/Route/Router.php\",\"line\":301,\"function\":\"main\",\"class\":\"OC\\\\AppFramework\\\\App\",\"type\":\"::\",\"args\":[\"OC\\\\Core\\\\Controller\\\\LoginController\",\"tryLogin\",{\"__class__\":\"OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer\"},{\"_route\":\"core.login.tryLogin\"}]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/lib/base.php\",\"line\":1000,\"function\":\"match\",\"class\":\"OC\\\\Route\\\\Router\",\"type\":\"->\",\"args\":[\"/login\"]},{\"file\":\"/snap/nextcloud/211119415/nextcloud/index.php\",\"line\":36,\"function\":\"handleRequest\",\"class\":\"OC\",\"type\":\"::\",\"args\":[]}],\"File\":\"/snap/nextcloud/211119415/nextcloud/lib/private/DB/Exceptions/DbalException.php\",\"Line\":71,\"Previous\":{\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception
Dec  5 16:31:42 syncloud slapd[769]: conn=2633 op=2 UNBIND
Dec  5 16:31:42 syncloud slapd[769]: conn=2633 fd=10 closed
Dec  5 16:31:42 syncloud syncloud nginx: 192.168.XXX.XXX - - [05/Dec/2021:16:31:42 +0000] "POST /login HTTP/1.1" 500 4510 "-" "iPhone J\xF6rg XXXX (iOS Files)"
Dec  5 16:31:42 syncloud syncloud nginx: 192.168.XXX.XXX - - [05/Dec/2021:16:31:42 +0000] "POST /login HTTP/2.0" 500 4497 "-" "iPhone J\xF6rg XXXX (iOS Files)"
Dec  5 16:31:42 syncloud snapd[362]: 2021/12/05 16:31:42.793908 store.go:825: snapid: notes.19040763
Dec  5 16:31:42 syncloud syncloud nginx: 192.168.XXX.XXX - - [05/Dec/2021:16:31:42 +0000] "GET /core/l10n/de.js?v=742d14c5-0 HTTP/2.0" 200 22104 "-" "iPhone J\xF6rg XXXX (iOS Files)"
Dec  5 16:31:43 syncloud snapd[362]: 2021/12/05 16:31:42.999942 store.go:825: snapid: users.210524196
Dec  5 16:31:43 syncloud syncloud nginx: 192.168.XXX.XXX - - [05/Dec/2021:16:31:43 +0000] "GET /core/img/background.png?v=2 HTTP/1.1" 200 9621 "-" "iPhone J\xF6rg XXXX (iOS Files)"
Dec  5 16:31:43 syncloud syncloud nginx: 192.168.XXX.XXX - - [05/Dec/2021:16:31:43 +0000] "GET /core/img/background.png?v=2 HTTP/2.0" 200 9621 "-" "iPhone J\xF6rg XXXX (iOS Files)"
Dec  5 16:31:43 syncloud syncloud nginx: 192.168.XXX.XXX - - [05/Dec/2021:16:31:43 +0000] "GET /core/img/logo/logo.svg?v=1 HTTP/2.0" 200 183 "-" "iPhone J\xF6rg XXXX (iOS Files)"
Dec  5 16:31:43 syncloud snapd[362]: 2021/12/05 16:31:43.204316 store.go:825: snapid: pihole.210320405
```

### Environment data

Ondroid XU4

**iOS version:** e.g. iOS 15.1

**Nextcloud iOS app version:** see More > 211119415

**Server operating system:**

**Web server:** nginx

**Database:** postgreSQL

**PHP version:**

**Nextcloud version:** see Nextcloud admin page

### PR DESCRIPTION
**Pull request by thisIsTheFoxe**
Use default app user agent for login. This will display *Nextcloud iOS app* in the user security settings.

- Fixes #1791 
- Fixes #1800 
- Fixes #1803 

- [x] Tested

### CODE REVIEW

**Comment by marinofaggiana** [comment]
Why you have removed the: 

let deviceName = UIDevice.current.name
let userAgent = deviceName + " " + "(iOS Files)"

it is not solved by removing pieces of code, but understanding why it is rejected

**Review by marinofaggiana — CHANGES_REQUESTED** [review]
Job incomplete

**Comment by thisIsTheFoxe** [comment]
@marinofaggiana I explained it in the linked issue. Using a device name with non-ascii characters causes the server (or the database) to throw an error, which makes it impossible to login. Also, in the rest of the app we always uses `CCUtility.getUserAgent()` which makes it very inconsistent when using the device name only in this instance. Furthermore, the server doesn't recognise this custom user agent as coming from the iOS app and consequently doesn't display it as such in the user settings.

If we want to change this, I think we should start at the server and agree on a unified format that can be parsed and includes the device name, version etc.

**Comment by marinofaggiana** [comment]
It's important the name of device so is distinguishable from the list of device registered, if exists a problem with the special char you can use the "encode" or write a routine for replace the not ascii with ascii i.e. : è -> e

**Comment by thisIsTheFoxe** [comment]
I agree. But the server doesn't just display the user agent. It should [detect](https://github.com/nextcloud/server/pull/3430) if a request was made from the iOS app. And if there is a device name it could display it as well. But I think just changing it without regard to how the server handles it might cause more confusion than it helps....

**Comment by marinofaggiana** [comment]
@Ivansss how works Talk about the name of device ?

**Comment by Ivansss** [comment]
> how works Talk about the name of device ?

in the Talk iOS app we use "device name (Nextcloud Talk)" as user agent for the login flow.
https://github.com/nextcloud/talk-ios/blob/master/NextcloudTalk/AuthenticationViewController.m#L77-L80

**Comment by marinofaggiana** [comment]
> I agree. But the server doesn't just display the user agent. It should [detect](https://github.com/nextcloud/server/pull/3430) if a request was made from the iOS app. And if there is a device name it could display it as well. But I think just changing it without regard to how the server handles it might cause more confusion than it helps....

This issue happens only with the device name contains special chars, why you remove all ??? you must only fixed.

Was a OLD PR (server/pull/3430), you can't remove code or rewrite code because it don't like or because you don't understand, please added the final encode for fix or close this PR that I do I, and before create new PR please ask question in the issue so we can look for an answer before writing code.

**Comment by thisIsTheFoxe** [comment]
I mean to me it looked like the way the server handles it was the intended way. I didn't find any issue, request, or documentation which would suggest that a different user agent should be used for the login flow. If I missed something I'm sorry.

Also, btw, I did leave a comment on the issue before opening this PR. And, since I would consider this an urgent bug that makes the app unusable if you cannot login, I thought it be best to just open this Pull *Request* to fix it as soon as possible...

**Review by Ivansss — APPROVED** [review]
Makes sense to me 👍

**Comment by marinofaggiana** [comment]
good

**Review by marinofaggiana — APPROVED** [review]

**Comment by marinofaggiana** [comment]
Thanks @thisIsTheFoxe @Ivansss

**Pull request merged**
