### PR TITLE
Open files from other apps

### PR DESCRIPTION
**Pull request by Ivansss**
Add ability to open files from other apps.
The app will listen to `nextcloud://open-file?url=(fileURL)&user=(user)` urls.

### CODE REVIEW

**Comment by mario** [comment]
Please make this brand able.

**Comment by marinofaggiana** [comment]
Thanks Ivan.

**Comment by mario** [comment]
@marinofaggiana why was this merged? It wasn't finished...

**Comment by marinofaggiana** [comment]
I & Ivan we are working on it, no worry

**Pull request merged**
