### PR TITLE
Allow user to choose granularity of Autoupload subfolders (year/month/day)

### PR DESCRIPTION
**Pull request by fservida**
Solves #2283
Tested in the simulator without issues, unable to test locally on device however.

Signed-off-by: Francesco Servida [git.fservida@gmail.com](mailto:git.fservida@gmail.com)

### CODE REVIEW

**Comment by fservida** [comment]
Simulator Screen Shot - iPhone 14 Pro - 2023-01-01 at 19 27 04
Simulator Screen Shot - iPhone 14 Pro - 2023-01-01 at 19 27 08
image

**Comment by fservida** [comment]
Currently only localized two files: Localizable.strings for EN and DE, unsure whethere there is a general file to also edit...
Tried to keep the code as clean as possible, but rarely program for iOS, probably there are better ways to handle, feel free to refactor as needed.

**Comment by marinofaggiana** [comment]
@fservida good job !! thanks !! will make some test. I am working on the refactory of the settings views but for now it is fine

**Comment by andyxheli** [comment]
Thank you so much!! What an amazing job.

**Comment by fservida** [comment]
Obsolete, check https://github.com/nextcloud/ios/pull/2386

**Pull request closed without merging**
