### PR TITLE
Add autoplay video option under Advanced settings

### PR DESCRIPTION
**Pull request by d-noble**
* Added an option to automatically start playing videos
* Setting is disabled by default

#### Added new toggle under Settings > Advanced
<kbd>
image
</kbd>

#### Demo

https://user-images.githubusercontent.com/16694155/170541693-212fe792-5709-45e1-9e09-92e2a292a215.mov

---
Signed-off-by: david <alexander.noble@live.com>

### CODE REVIEW

**Comment by marinofaggiana** [comment]
I don't like added new option for the behavior.... but, maybe, we can change the automatic auto-play from OFF to ON ....

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/ios/pull/2071/commits/d7b9bcd461b045194f8e0c961e5e6f936e61a2cf

Whats do you think ? @d-noble @Valdnet

**Comment by d-noble** [comment]
> [d7b9bcd](https://github.com/nextcloud/ios/commit/d7b9bcd461b045194f8e0c961e5e6f936e61a2cf)
> 
> Whats do you think ? @d-noble @Valdnet

I can agree with the decision to remove the option. 👍

**Comment by Valdnet** [comment]
In my opinion, a good solution proposed by @marinofaggiana.

**Comment by marinofaggiana** [comment]
ok you can try the solution from the V 4.4.1 build 7 in https://testflight.apple.com/join/RXEJbWj9

**Pull request closed without merging**
