### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by rakekniven**
Added link to v2.20.4

### CODE REVIEW

**Comment by rakekniven** [comment]
Hello @marinofaggiana 
You made another release and forget to send me one line.

Please merge this PR for updating changelog for older stuff.

**Comment by marinofaggiana** [comment]
Yes @rakekniven was a quickly update, now on AppStore.

**Comment by rakekniven** [comment]
Hello @marinofaggiana 
One idea: Instead of creating a branch for my changelog modification I can directly edit file on develop branch and you merge it to master.
What do you think?

**Comment by marinofaggiana** [comment]
Yes, @rakekniven ! Thanks

**Pull request merged**
