### PR TITLE
Set available offline enhancements

### LINKED ISSUE #1178: "Set as available offline" setting appears again when file is updated
### Expected behaviour                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
Set as available offline keeps the file offline, with option to remove as available offline.

### Actual behaviour                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
Set as available offline option shows again if the file was overwritten/updated.

### Steps to reproduce     
1. Set as available offline a file
2. On nextcloud desktop/webpage, upload and update the same file.
3. Set as available offline option appears again on the file on mobile

### Reasoning or why should it be changed/implemented?
This is confusing as users are not sure if the setting persist if the file gets updated as the "Set as available offline" option shows again.

### iOS version
13.3.1

### App version
2.25.9.2

### LINKED ISSUE #1797: Offline use - Download icon is not shown after set to "available offline"
Frequency
Every Time

Actions Performed
1. Open the app
2. Click on context menu of any file
3. click on "Set as available offline"
4. check green icon of file
5. click on any folder or file
6. go back
7. check again green icon

Expected Result
After set to "available offline" the green icon changes from check mark to downloaded icon.

Actual Result
After set to "available offline" the green icon doesn't change from check mark to download icon. You have to open any file or folder to update the icon of file.

### PR DESCRIPTION
**Pull request by thisIsTheFoxe**
Allow user to set multiple files / folders as available offline at once, while selecting.

FIx #1178
Fix #1797

- Add "Available offline" to select-`NCMenu`
- Prefer 'not offline'. I.e. if a user selects files that are mixed available offline, the option is to remove those who are offline, rather than making everything available offline
- If more than 3 file / folders are selected, ask for confirmation

### CODE REVIEW

**Comment by marinofaggiana** [comment]
@thisIsTheFoxe can you rebase this PR ?

**Comment by marinofaggiana** [comment]
@thisIsTheFoxe is ready for test ?

**Comment by thisIsTheFoxe** [comment]
@marinofaggiana yes, this PR is ready for review

**Comment by marinofaggiana** [comment]
- If file is already in local the set as available offline re-download the file
- I don't know if if a new issue but with the "Open in..." the UI result blocked untile the file is completely downloaded

https://user-images.githubusercontent.com/8616947/155175754-feabc6e9-31ee-402c-aaf0-442573676928.mov

**Review by marinofaggiana — CHANGES_REQUESTED** [review]
@thisIsTheFoxe look the video

**Comment by marinofaggiana** [comment]
> @marinofaggiana
> 
> * Yes, this is the same behaviour as it was before. I assume that's on purpose, so that you always have the newest version..?

Probably... ok.

> * That's also the same as before. I don't like it, but it's out-of-scope for this PR..

Yes, need another PR

**Review by marinofaggiana — APPROVED** [review]

**Pull request merged**
