### PR TITLE
Use CollaboraOnlineWebViewKeyboardManager for rich document editing

### PR DESCRIPTION
**Pull request by tml1024**
If the version of Collabora Online that gets used is prepared to use
CollaboraOnlineWebViewKeyboardManager, this will mean a much more
reliable handling of the on-screen keyboard while using it.

Include the NOTICE file from CollaboraOnlineWebViewKeyboardManager in
a NOTICE file here, as required by its license.

### CODE REVIEW

**Comment by shw26y10** [comment]
Good

**Comment by marinofaggiana** [comment]
@tml1024 thanks !!! soon I look your job !!

**Comment by marinofaggiana** [comment]
Thanks a lot @tml1024 !

**Comment by marinofaggiana** [comment]
@tml1024 the CollaboraOnlineWebViewKeyboardManager has issue with our NCViewerRichdocument, can you try the behavior in the develop branch, for now I disable it. What should improve ?

**Pull request closed without merging**
