### PR TITLE
[Un-Revert] Talk notification

### PR DESCRIPTION
**Pull request by thisIsTheFoxe**
Reverts nextcloud/iOS#1772

### Related: 
- https://github.com/nextcloud/spreed/pull/6644#pullrequestreview-820309005

### CODE REVIEW

**Comment by marinofaggiana** [comment]
What's happen ? I have already approved this PR

**Comment by thisIsTheFoxe** [comment]
@marinofaggiana #1772 reverted it, because [as you requested](https://github.com/nextcloud/ios/pull/1768#issuecomment-979860067).
But please wait, with merging some more.. there's just been an update about the notification API..

**Comment by marinofaggiana** [comment]
I have already merged (after) ...  ping me when ready.

**Review by Ivansss — APPROVED** [review]
LGTM 👍

**Comment by marinofaggiana** [comment]
I have no idea what this PR is, but if ivan has approved, ok

**Review by marinofaggiana — APPROVED** [review]

**Pull request merged**
