### PR TITLE
added InfoPlist ( l10n/i18n Translation )

### PR DESCRIPTION
**Pull request by marinofaggiana**
https://github.com/nextcloud/ios/issues/1801

### CODE REVIEW

**Comment by marinofaggiana** [comment]
@Ivansss who can added the InfoPlist Localization on Transifex ?

**Comment by Ivansss** [comment]
We could add in this PR the transifex configuration as in Talk:
https://github.com/nextcloud/talk-ios/blob/master/.tx/config#L11-L16

**Comment by marinofaggiana** [comment]
mmm good but I think required Transifex conf ?

Note:

@Ivansss 

NSCameraUsageDescription = "Camera access is required to scan documents and make photo and video.";
^
error: validation failed: Couldn't parse property list because the input data was in an invalid format

**Comment by nickvergessen** [comment]
Syncing worked

**Pull request merged**
